name: achilles_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas=2.2.2
  - numpy=1.26.4
  - scanpy=1.10.1
  - squidpy=1.3.1
  - napari=0.4.19
  - scikit-learn=1.4.2
  - umap-learn=0.5.5
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - tqdm=4.66.4
  - anndata=0.10.6
  - h5py=3.11.0
  - jupyterlab=4.0.6
  - requests=2.31.0
  - pyyaml=6.0.1
  - jupyter=1.0.0
  - notebook=7.2.0
  - ipykernel=6.29.4
  - opencv=4.9.0
  - pillow=10.3.0
  - networkx=3.3
  - statsmodels=0.14.2
  - pip:
      - torch==2.2.2
      - torchvision==0.17.2
      - napari-spatialdata==0.5.4
      - nico-sc-sp==1.4.0
      - google-cloud-storage==2.16.0